version: '3.0'

services:
  client:
    build: ./client
#    volumes:
#      - "./client:/app"
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: ./api
 #   volumes:
 #     - "./api:/app"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: 3005BookStore
    volumes:
        - ./sql/ddl.sql:/docker-entrypoint-initdb.d/sql/ddl.sql
    ports:
        - "5433:5432"
