version: '3.2'

services:
  client:
    build: ./client
#    volumes:
#      - "./client:/app"
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - bookstore

  api:
    build: ./api
 #   volumes:
 #     - "./api:/app"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - bookstore
  db:
    image: postgres
#    hostname: postgres
    environment: 
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
#    volumes:
#        - database_postgres:/var/lib/postgresql/data
#        - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
#    ports:
#        - "5433:5432"
    networks:
        - bookstore
        
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
        - db
    ports:
        - "5555:80"
    links:
        - db
#        - "db:database"
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: 1234
    restart: unless-stopped
    networks:
      - bookstore

volumes:
    api:
    database_postgres:

networks:
    bookstore:
        driver: bridge